# Generated by Django 2.1.2 on 2019-03-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0024_auto_20190224_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height_unit',
            field=models.CharField(blank=True, choices=[('metric', 'metric'), ('imperial', 'imperial')], max_length=10, verbose_name='Height unit preference'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'kilogram'), ('lb', 'pounds'), ('st', 'stones')], max_length=10, verbose_name='Weight unit preference'),
        ),
    ]
