# Generated by Django 2.1.2 on 2019-04-19 12:54

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190325_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='profile_pictures', verbose_name='profile_picture'),
        ),
    ]
