# Generated by Django 2.1.2 on 2018-11-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171024_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, max_length=120, verbose_name='Number'),
        ),
    ]
