# Generated by Django 2.1.2 on 2018-11-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Date Of Birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'I would rather not say')], max_length=4, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='user',
            name='height_unit',
            field=models.CharField(blank=True, choices=[('ft', 'feet and inches'), ('cm', 'centimeters')], max_length=4, verbose_name='Height unit preference'),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('st', 'stones'), ('lb', 'pounds'), ('kg', 'kilogram')], max_length=4, verbose_name='Weight unit preference'),
        ),
    ]
