# Generated by Django 2.1.2 on 2019-04-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190419_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invited',
            field=models.BooleanField(default=False, verbose_name='Invited'),
        ),
    ]
