# Generated by Django 2.1.2 on 2018-12-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181129_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height_unit',
            field=models.CharField(blank=True, choices=[('cm', 'centimeters'), ('ft', 'feet and inches')], max_length=4, verbose_name='Height unit preference'),
        ),
    ]
