# Generated by Django 2.1.2 on 2020-04-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_invited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height_unit',
            field=models.CharField(blank=True, choices=[('metric', 'metric'), ('imperial', 'imperial')], default='metric', max_length=10, verbose_name='Height unit preference'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('metric', 'metric'), ('imperial', 'imperial')], default='metric', max_length=10, verbose_name='Weight unit preference'),
        ),
    ]
