# Generated by Django 2.1.2 on 2018-12-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181219_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'kilogram'), ('st', 'stones'), ('lb', 'pounds')], max_length=4, verbose_name='Weight unit preference'),
        ),
    ]
