# Generated by Django 2.1.2 on 2018-12-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181219_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height_unit',
            field=models.CharField(blank=True, choices=[('ft', 'feet and inches'), ('cm', 'centimeters')], max_length=4, verbose_name='Height unit preference'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('st', 'stones'), ('kg', 'kilogram'), ('lb', 'pounds')], max_length=4, verbose_name='Weight unit preference'),
        ),
    ]
