# Generated by Django 2.1.2 on 2018-12-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20181227_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height_unit',
            field=models.CharField(blank=True, choices=[('cm', 'centimeters'), ('ft', 'feet and inches')], max_length=4, verbose_name='Height unit preference'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('lb', 'pounds'), ('kg', 'kilogram'), ('st', 'stones')], max_length=4, verbose_name='Weight unit preference'),
        ),
    ]
