# Generated by Django 2.1.2 on 2018-12-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20181227_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'kilogram'), ('lb', 'pounds'), ('st', 'stones')], max_length=4, verbose_name='Weight unit preference'),
        ),
    ]
