# Generated by Django 2.1.2 on 2019-01-08 18:39

from django.db import migrations, models
import uuid_upload_path.storage
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20181231_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=uuid_upload_path.storage.upload_to, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='user',
            name='image_poi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name="image's Point of Interest"),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('st', 'stones'), ('lb', 'pounds'), ('kg', 'kilogram')], max_length=4, verbose_name='Weight unit preference'),
        ),
    ]
