# Generated by Django 2.1.2 on 2019-02-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190206_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height_unit',
            field=models.CharField(blank=True, choices=[('imperial', 'imperial'), ('metric', 'metric')], max_length=10, verbose_name='Height unit preference'),
        ),
    ]
