# Generated by Django 2.1.2 on 2018-12-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20181225_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Notes'),
        ),
    ]
