# Generated by Django 2.1.2 on 2019-03-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='kind',
            field=models.CharField(blank=True, choices=[('MEALPLAN', 'MEAL PLAN'), ('CLIENTAGREEMENT', 'CLIENT AGREEMENT'), ('PARQ', 'PARQ'), ('GUARANTEE', 'GUARANTEE'), ('MISC', 'MISC')], max_length=50, verbose_name='type'),
        ),
    ]
