# Generated by Django 2.1.2 on 2018-12-30 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('body_water', models.FloatField(verbose_name='Body Water')),
                ('proteins', models.FloatField(verbose_name='Proteins')),
                ('minerals', models.FloatField(verbose_name='Minerals')),
                ('body_fat', models.FloatField(verbose_name='Body fat')),
                ('body_fat_percentage', models.FloatField(verbose_name='Body fat percentage')),
                ('muscle_mass', models.FloatField(verbose_name='Muscle Mass')),
                ('muscle_mass_percentage', models.FloatField(verbose_name='muscle mass percentage')),
                ('visceral_fat_mass', models.FloatField(verbose_name='visteral fat mass')),
                ('body_type', models.FloatField(verbose_name='Body Type')),
                ('biological_age', models.IntegerField(verbose_name='Biological Age')),
                ('hips', models.FloatField(verbose_name='Hips')),
                ('chest', models.FloatField(verbose_name='Chest')),
                ('shoulders', models.FloatField(verbose_name='Shoulders')),
                ('left_arm', models.FloatField(verbose_name='Left Arm')),
                ('right_arm', models.FloatField(verbose_name='Right Arm')),
                ('left_leg', models.FloatField(verbose_name='Left Leg')),
                ('right_leg', models.FloatField(verbose_name='Right Leg')),
                ('waist', models.FloatField(verbose_name='Waist')),
                ('lean_mass_trunk', models.FloatField(verbose_name='lean_mass_trunk')),
                ('lean_mass_left_arm', models.FloatField(verbose_name='Lean Mass Left Arm')),
                ('lean_mass_right_arm', models.FloatField(verbose_name='Lean Mass Right Arm')),
                ('lean_mass_left_leg', models.FloatField(verbose_name='Lean Mass Left Leg')),
                ('lean_mass_right_leg', models.FloatField(verbose_name='Lean Mass Right Leg')),
                ('systolic_blood_pressure', models.FloatField(verbose_name='Systolic Blood Pressure')),
                ('diastolic_blood_pressure', models.FloatField(verbose_name='Diatolic Blood Pressure')),
                ('blood_sugar', models.FloatField(verbose_name='Blood Sugar')),
                ('vo2max', models.FloatField(verbose_name='VO2Max')),
                ('resting_heart_rate', models.FloatField(verbose_name='Resting Heart Rate')),
                ('photo_front', versatileimagefield.fields.VersatileImageField(upload_to='checkin_images/', verbose_name='Front Photo')),
                ('photo_side', versatileimagefield.fields.VersatileImageField(upload_to='checkin_images/', verbose_name='Side Photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkin_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Name of Meal')),
                ('carbohydrate', models.IntegerField(verbose_name='Carbohydrate')),
                ('fat', models.IntegerField(verbose_name='Fat')),
                ('protein', models.IntegerField(verbose_name='Protein')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mealplan_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('weekly_commentry', 'Weekly Commentry')], max_length=120, verbose_name='Message type')),
                ('read', models.BooleanField(default=False, verbose_name='Has been read by the recipient')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Programme Name')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programme_coach', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programme_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('weight', models.FloatField(verbose_name='Weight')),
                ('measured_on', models.DateField(verbose_name='Measured on')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weight_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
