# Generated by Django 2.1.2 on 2019-02-06 15:44

import datetime
from django.contrib.postgres.operations import HStoreExtension
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_auto_20190108_1839'),
    ]

    operations = [
        HStoreExtension(),
        migrations.RemoveField(
            model_name='checkin',
            name='biological_age',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='blood_sugar',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='body_fat',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='body_fat_percentage',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='body_water',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='chest',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='diastolic_blood_pressure',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='hips',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='lean_mass_left_arm',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='lean_mass_left_leg',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='lean_mass_right_arm',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='lean_mass_right_leg',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='lean_mass_trunk',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='left_arm',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='left_leg',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='minerals',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='muscle_mass',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='muscle_mass_percentage',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='photo_front',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='photo_side',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='proteins',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='resting_heart_rate',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='right_arm',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='right_leg',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='shoulders',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='systolic_blood_pressure',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='visceral_fat_mass',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='vo2max',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='waist',
        ),
        migrations.AddField(
            model_name='checkin',
            name='accuniq_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkin',
            name='date_of_checkin',
            field=models.DateField(default=datetime.datetime(2019, 2, 6, 15, 44, 22, 39008, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
