# Generated by Django 2.1.2 on 2019-02-06 18:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_auto_20190206_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='accuniq_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 18, 53, 12, 488851, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
