# Generated by Django 2.1.2 on 2019-02-18 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0005_checkin_accuniq_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('photo_front_profile', versatileimagefield.fields.VersatileImageField(upload_to='checkin_images', verbose_name='front_profile')),
                ('photo_side_profile', versatileimagefield.fields.VersatileImageField(upload_to='checkin_images', verbose_name='side_profile')),
                ('waist', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='waist')),
                ('hips', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='hips')),
                ('chest', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='chest')),
                ('shoulders', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='shoulders')),
                ('left_arm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='left_arm')),
                ('right_arm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='right_arm')),
                ('left_leg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='left_leg')),
                ('right_leg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='right_leg')),
                ('date_of_checkin', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
