# Generated by Django 2.1.2 on 2019-02-22 06:43

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_measurements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurements',
            name='user',
        ),
        migrations.AddField(
            model_name='checkin',
            name='chest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='chest'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='hips',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='hips'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='left_arm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='left_arm'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='left_leg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='left_leg'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='photo_front_profile',
            field=versatileimagefield.fields.VersatileImageField(default=None, upload_to='checkin_images', verbose_name='front_profile'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='photo_side_profile',
            field=versatileimagefield.fields.VersatileImageField(default=None, upload_to='checkin_images', verbose_name='side_profile'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='right_arm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='right_arm'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='right_leg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='right_leg'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='shoulders',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='shoulders'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='waist',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='waist'),
        ),
        migrations.DeleteModel(
            name='Measurements',
        ),
    ]
