# Generated by Django 2.1.2 on 2019-02-24 10:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0007_auto_20190222_0643'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('user', 'date_of_checkin')},
        ),
    ]
