# Generated by Django 2.1.2 on 2019-04-03 15:03

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0009_auto_20190224_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Comment')),
                ('kind', models.CharField(choices=[('C', 'CREDITED'), ('D', 'DEBITED')], max_length=4, verbose_name='credit/debit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='programme',
        ),
        migrations.AddField(
            model_name='programme',
            name='sessions',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AddField(
            model_name='sessionledger',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessionledger_programme', to='fitness.Programme'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holiday_programme', to='fitness.Programme'),
        ),
    ]
