# Generated by Django 2.1.2 on 2019-04-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_auto_20190403_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
