# Generated by Django 2.1.2 on 2019-04-14 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0011_programme_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetWeight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('target_weight', models.FloatField(verbose_name='Weight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weight_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='weight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_weight_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
