# Generated by Django 2.1.2 on 2019-04-14 11:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0012_auto_20190414_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetweight',
            name='set_on',
            field=models.DateField(default=datetime.datetime(2019, 4, 14, 11, 41, 52, 120620, tzinfo=utc), verbose_name='Set on'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='measured_on',
            field=models.DateField(default=datetime.datetime(2019, 4, 14, 11, 41, 52, 121013, tzinfo=utc), verbose_name='Measured on'),
        ),
    ]
