# Generated by Django 2.1.2 on 2019-04-14 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0013_auto_20190414_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetweight',
            name='set_on',
            field=models.DateField(default=datetime.datetime(2019, 4, 14, 17, 28, 58, 810674, tzinfo=utc), verbose_name='Set on'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='measured_on',
            field=models.DateField(default=datetime.datetime(2019, 4, 14, 17, 28, 58, 811090, tzinfo=utc), verbose_name='Measured on'),
        ),
    ]
