# Generated by Django 2.1.2 on 2019-04-14 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0014_auto_20190414_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetweight',
            name='set_on',
        ),
        migrations.AddField(
            model_name='targetweight',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='end_date'),
        ),
        migrations.AddField(
            model_name='targetweight',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='start_date'),
        ),
        migrations.AddField(
            model_name='targetweight',
            name='start_weight',
            field=models.FloatField(default=0, verbose_name='Start Weight'),
        ),
        migrations.AlterField(
            model_name='targetweight',
            name='target_weight',
            field=models.FloatField(default=0, verbose_name='Target Weight'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='measured_on',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Measured on'),
        ),
    ]
