# Generated by Django 2.1.2 on 2019-04-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0015_auto_20190414_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='targetweight',
            old_name='end_date',
            new_name='target_date',
        ),
    ]
