# Generated by Django 2.1.2 on 2019-04-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0016_auto_20190414_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, verbose_name='Content'),
        ),
    ]
