# Generated by Django 2.1.2 on 2019-04-25 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0018_auto_20190423_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mealplan_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
