# Generated by Django 2.1.2 on 2019-04-25 16:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0019_auto_20190425_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealplan',
            old_name='meal_percentage',
            new_name='meal_breakup',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='daily_percentages',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='daily_breakup',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
