# Generated by Django 2.1.2 on 2019-05-06 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0020_auto_20190425_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetweight',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='targetweight',
            name='start_weight',
        ),
    ]
