# Generated by Django 2.1.2 on 2019-05-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0021_auto_20190506_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='blood_sugar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='blood_sugar'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='diastolic_blood_pressure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='diastolic_blood_pressure'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='systolic_blood_pressure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='systolic_blood_pressure'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='vo2_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='vo2_max'),
        ),
    ]
