# Generated by Django 2.1.2 on 2019-05-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0022_auto_20190518_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='resting_heart_rate',
            field=models.IntegerField(default=0, verbose_name='resting heart rate'),
        ),
    ]
