# Generated by Django 2.1.2 on 2019-06-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0024_accuniqdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accuniqdata',
            name='csvfile',
            field=models.FileField(upload_to='accuniq', verbose_name='accuniq csvfile'),
        ),
    ]
