# Generated by Django 2.1.2 on 2019-06-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0025_auto_20190604_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='accuniq_id',
            field=models.CharField(default='', max_length=21, verbose_name='Accuniq Id'),
        ),
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('accuniq_id', 'accuniq_timestamp')},
        ),
    ]
