# Generated by Django 2.1.2 on 2019-06-04 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0026_auto_20190604_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkin_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
