# Generated by Django 2.1.2 on 2019-06-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0027_auto_20190604_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='date_of_checkin',
            field=models.DateField(blank=True, null=True, verbose_name='Date of checkin'),
        ),
    ]
