# Generated by Django 2.1.2 on 2019-07-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0028_auto_20190604_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('checkin-commenty', 'Checkin Commentry'), ('weekly-commentry', 'Weekly Commentry'), ('misc', 'MISCELLANEOUS')], max_length=120, verbose_name='Message type'),
        ),
    ]
