# Generated by Django 2.1.2 on 2019-07-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0029_auto_20190708_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('checkin-commentry', 'Checkin Commentry'), ('weekly-commentry', 'Weekly Commentry'), ('misc', 'MISCELLANEOUS')], max_length=120, verbose_name='Message type'),
        ),
    ]
