# Generated by Django 2.1.2 on 2019-07-15 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('fitness', '0031_checkin_coach_comment'), ('fitness', '0032_auto_20190713_1059'), ('fitness', '0033_auto_20190715_1935')]

    dependencies = [
        ('fitness', '0030_auto_20190709_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='comment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment_of', to='fitness.Message'),
        ),
    ]
