# Generated by Django 2.1.2 on 2019-07-12 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0030_auto_20190709_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='coach_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fitness.Message'),
        ),
    ]
