# Generated by Django 2.1.2 on 2019-07-13 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0031_checkin_coach_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='coach_comment',
        ),
        migrations.AddField(
            model_name='checkin',
            name='comment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='comment_of', to='fitness.Message'),
            preserve_default=False,
        ),
    ]
