# Generated by Django 2.1.2 on 2019-10-28 18:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0031_checkin_coach_comment_squashed_0033_auto_20190715_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('C', 'CREDITED'), ('D', 'DEBITED')], max_length=4, verbose_name='credit/debit')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leaveledger2programme', to='fitness.Programme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sessionledger',
            name='programme',
        ),
        migrations.AddField(
            model_name='holiday',
            name='programme_end_date',
            field=models.DateField(default=datetime.datetime(2001, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holiday',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holiday2programme', to='fitness.Programme'),
        ),
        migrations.DeleteModel(
            name='SessionLedger',
        ),
    ]
