# Generated by Django 2.1.2 on 2019-07-15 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0032_auto_20190713_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='comment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment_of', to='fitness.Message'),
        ),
    ]
