# Generated by Django 2.1.2 on 2020-02-24 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0033_checkin_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accuniqdata',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuniqdata_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='comment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_of', to='fitness.Message'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkin_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday2programme', to='fitness.Programme'),
        ),
        migrations.AlterField(
            model_name='leaveledger',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaveledger2programme', to='fitness.Programme'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mealplan_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='targetweight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_weight_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
