# Generated by Django 2.1.2 on 2020-05-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0036_auto_20200402_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Weight'),
        ),
    ]
