# Generated by Django 2.1.2 on 2020-05-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0037_auto_20200506_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='blood_sugar',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='blood_sugar'),
        ),
    ]
